version: '3.8'
services:
  name-postgres:
    image: postgres
    container_name: name-postgres
    restart: always
    ports:
      - '5430:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - test_pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - name-network

volumes:
  test_pgdata:

networks:
  name-network:
    external: true
